
configdb:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Pass: **************1.
  Schema:
    Connect: chengken.sr_slow_query_manager

common:
# pstack命令所在位置
  Pstack: pstack
# jstack命令所在位置
  Jstack: /u/StarRocks/agent/jdk-8/bin/jstack
# SSH账号
  User: starrocks
# SSH端口
  Port: 22
# 账号私钥
  Private: /u/users/svccndlopsns/.ssh/id_rsa
# 打包回传日志，放在这
  LogPath: /u1/dlopsnas/chengken/


logger:
  LogPath: /u/users/svccndlopsns/chengken/log/Support


